# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\add_dance_window.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddDanceWindow(object):
    def setupUi(self, AddDanceWindow):
        AddDanceWindow.setObjectName("AddDanceWindow")
        AddDanceWindow.setEnabled(True)
        AddDanceWindow.resize(434, 382)
        self.centralwidget = QtWidgets.QWidget(AddDanceWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.category_label = QtWidgets.QLabel(self.centralwidget)
        self.category_label.setObjectName("category_label")
        self.gridLayout.addWidget(self.category_label, 0, 0, 1, 1)
        self.category_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.category_comboBox.setObjectName("category_comboBox")
        self.category_comboBox.addItem("")
        self.category_comboBox.addItem("")
        self.category_comboBox.addItem("")
        self.category_comboBox.addItem("")
        self.gridLayout.addWidget(self.category_comboBox, 0, 1, 1, 1)
        self.name_label = QtWidgets.QLabel(self.centralwidget)
        self.name_label.setObjectName("name_label")
        self.gridLayout.addWidget(self.name_label, 1, 0, 1, 1)
        self.name_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.name_lineEdit.setObjectName("name_lineEdit")
        self.gridLayout.addWidget(self.name_lineEdit, 1, 1, 1, 1)
        self.tags_label = QtWidgets.QLabel(self.centralwidget)
        self.tags_label.setObjectName("tags_label")
        self.gridLayout.addWidget(self.tags_label, 2, 0, 1, 1)
        self.tags_label_2 = QtWidgets.QLabel(self.centralwidget)
        self.tags_label_2.setObjectName("tags_label_2")
        self.gridLayout.addWidget(self.tags_label_2, 2, 1, 1, 1)
        self.tags_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.tags_comboBox.setEditable(True)
        self.tags_comboBox.setObjectName("tags_comboBox")
        self.gridLayout.addWidget(self.tags_comboBox, 3, 1, 1, 1)
        self.description_label = QtWidgets.QLabel(self.centralwidget)
        self.description_label.setObjectName("description_label")
        self.gridLayout.addWidget(self.description_label, 4, 0, 1, 1)
        self.description_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.description_textEdit.setMinimumSize(QtCore.QSize(0, 0))
        self.description_textEdit.setObjectName("description_textEdit")
        self.gridLayout.addWidget(self.description_textEdit, 4, 1, 2, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 138, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 5, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem1 = QtWidgets.QSpacerItem(158, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.submit_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.submit_pushButton.sizePolicy().hasHeightForWidth())
        self.submit_pushButton.setSizePolicy(sizePolicy)
        self.submit_pushButton.setObjectName("submit_pushButton")
        self.horizontalLayout.addWidget(self.submit_pushButton)
        self.cancel_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cancel_pushButton.sizePolicy().hasHeightForWidth())
        self.cancel_pushButton.setSizePolicy(sizePolicy)
        self.cancel_pushButton.setObjectName("cancel_pushButton")
        self.horizontalLayout.addWidget(self.cancel_pushButton)
        self.clear_pushButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clear_pushButton.sizePolicy().hasHeightForWidth())
        self.clear_pushButton.setSizePolicy(sizePolicy)
        self.clear_pushButton.setObjectName("clear_pushButton")
        self.horizontalLayout.addWidget(self.clear_pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        AddDanceWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddDanceWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 434, 21))
        self.menubar.setObjectName("menubar")
        AddDanceWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddDanceWindow)
        self.statusbar.setObjectName("statusbar")
        AddDanceWindow.setStatusBar(self.statusbar)

        self.retranslateUi(AddDanceWindow)
        QtCore.QMetaObject.connectSlotsByName(AddDanceWindow)

    def retranslateUi(self, AddDanceWindow):
        _translate = QtCore.QCoreApplication.translate
        AddDanceWindow.setWindowTitle(_translate("AddDanceWindow", "Add Dance Move"))
        self.category_label.setText(_translate("AddDanceWindow", "Category"))
        self.category_comboBox.setItemText(0, _translate("AddDanceWindow", "Technique/Step"))
        self.category_comboBox.setItemText(1, _translate("AddDanceWindow", "Concept"))
        self.category_comboBox.setItemText(2, _translate("AddDanceWindow", "Set"))
        self.category_comboBox.setItemText(3, _translate("AddDanceWindow", "Choreography"))
        self.name_label.setText(_translate("AddDanceWindow", "Name"))
        self.name_lineEdit.setPlaceholderText(_translate("AddDanceWindow", "Enter the name of the move"))
        self.tags_label.setText(_translate("AddDanceWindow", "Tags"))
        self.tags_label_2.setText(_translate("AddDanceWindow", "Enter tags below, separating with commas"))
        self.description_label.setText(_translate("AddDanceWindow", "Description"))
        self.submit_pushButton.setText(_translate("AddDanceWindow", "Submit"))
        self.cancel_pushButton.setText(_translate("AddDanceWindow", "Cancel"))
        self.clear_pushButton.setText(_translate("AddDanceWindow", "Clear"))
